version: '3'
services:

  rubyprac:
    build: .
    container_name: rubyprac
    tty: true
    volumes:
        - "./src/:/usr/app/"

  mysql-for-ar:
    image: mysql:5.7
    container_name: mysql-for-ar
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: CREATE DATABASE active_record_test;
      # mysql -u root -proot
      # use active_record_test;
    volumes:
      - db-volume:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/db/schema.sql:/docker-entrypoint-initdb.d/schema.sql


volumes:
  db-volume:
          