# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

gem "pry"
gem "erb"
gem "activerecord"
gem "mysql2"
# https://madogiwa0124.hatenablog.com/entry/2019/05/26/144214
gem "activesupport"